services:
  permission:
    image: rest-permission:v1
    build:
      context: .
    ports:
      - 8082:8080
    networks:
      - hireben-network
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      APP_SERVER_PORT: 8080
      DEMO_SERVICE_ENVIRONMENT: dev
      DEMO_SERVICE_REST_PERMISSION_ID: REST_PERMISSION
      DEMO_SERVICE_REST_PERMISSION_SECRET_KEY: hireBenDemoSecretKey
      DEMO_DATABASE_POSTGRES_HOST: postgres
      DEMO_DATABASE_POSTGRES_PORT: 5432
      DEMO_DATABASE_POSTGRES_DB: hireben-db
      DEMO_DATABASE_POSTGRES_USER: hirebenDemoDbUser
      DEMO_DATABASE_POSTGRES_PASSWORD: hireBenDemoDbPassword
      APP_DATABASE_POOL_CONN_MAX: 5
      APP_DATABASE_POOL_CONN_MIN: 1
      APP_DATABASE_SHOW_SQL: true
      
  postgres:
    image: postgres:alpine
    ports:
      - 5432:5432
    networks:
      - hireben-network
    volumes:
      - hireben_db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: hireben-db
      POSTGRES_USER: hirebenDemoDbUser
      POSTGRES_PASSWORD: hireBenDemoDbPassword
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "hirebenDemoDbUser", "-d", "hireben-db"]
      interval: 5s
      timeout: 3s
      retries: 1
      start_period: 5s
      start_interval: 10s
      
networks:
  hireben-network:
    external: true

volumes:
  hireben_db_data: